### ISSUE TITLE
[extend applicability] odd image size, ho, wo not evenly divided by gemm_n_per_block, fwd/bwd

### ISSUE THREAD

**Issue by carlushuang** [ROCmSoftwarePlatform/iGEMMgen#14]
merge(ho, wo) => dim_b, indeed we extend dim_b to modulo of gemm_n_per_block. This is the same for fwd/bwd. for wrw, dim_b is along gemm_k dimension, so may treat it differently

**Comment by JehandadKhan** [comment]
FP32 on gfx908 would be priority

**Comment by carlushuang** [comment]
@JehandadKhan Yes. And ideally this technique of padded kernel should be able to apply to other arch, other precision.
